### ISSUE TITLE
Some tests fail occasionally due to precision/rounding errors

### ISSUE THREAD

**Issue by belson17** [belson17/modred#14]
For example:
FAIL: test_compute_proj_coeffs (testdmd.TestDMDHandles)
FAIL: test_compute_model (testera.testERA)

**Comment by jhtu** [comment]
Fixed this by rewriting the tests for POD, BPOD, and DMD to check mathematical properties, rather than just doing duplicate computations.  Should be released as part of version 2.1.0.
