### ISSUE TITLE
Remove dependency on future library

### ISSUE THREAD

**Issue by cwrowley** [belson17/modred#2]
It is great that Pierre Augier updated the code to make it compatible with Python 3.  However, now the package requires the `future` module, both in python2 and python3.  It would be good to remove this dependency.  (I see no reason why we need this, as we are doing nothing terribly fancy in our code, so it should be straightforward to make it compatible with both python 2.7 and python3 without an additional package.)

**Comment by jhtu** [comment]
Removed dependency on future module.  Instead, use our own (new) py2to3 module, which only includes fixes for the Python 2 vs 3 issues that we actually run into in modred.  The main things to deal with were the use of range vs xrange, print statements, and execfile.
