### ISSUE TITLE
ERA has error with Python 2.6.1 numpy 1.13.1

### ISSUE THREAD

**Issue by belson17** [belson17/modred#23]
Something about an IndexError. 
![console_command_testera](https://user-images.githubusercontent.com/5126183/30726393-685da468-9eff-11e7-8fd8-88a063a76b99.PNG)

**Comment by jhtu** [comment]
It looks like this is actually a Python 3 error, based on the stack trace above.  That would make sense since then num_time_steps / 2 would be a float, which would generate an IndexError.

**Comment by jhtu** [comment]
In any case, this has been fixed.
