### ISSUE TITLE
balanced truncation order issue

### ISSUE THREAD

**Issue by shaesaert** [belson17/modred#25]
There seems to be an error in the balanced_truncation function (modred.util), it does not take orders that are lower than Len(E). 

It can be fixed by changing:
https://github.com/belson17/modred/blob/c84f67afe03fd1f18fdd7bb99e964c3c11a2040b/modred/util.py#L481

to 
```python
SL = Lo.dot(U[:,:order]).dot(np.diag(E[:order]**-0.5))
SR = Lc.dot(V[:,:order]).dot(np.diag(E[:order]**-0.5))
```

**Comment by belson17** [comment]
Thanks for catching this. I'll create an issue in github and we should have
it fixed in the next release.
Best,
Brandt
