### ISSUE TITLE
Tutorials issue

### ISSUE THREAD

**Issue by benoitpaillard** [belson17/modred#26]
Hi all,

I believe tutorials have not been updated : 

`mr.range` needs to be replace with `range`, with the following at the beginning
`from future.builtins import range`

and `compute_POD_arrays_snaps_method `needs to be replaced by `mr.compute_POD_matrices_snaps_method`

**Comment by jhtu** [comment]
Hi Benoit,

Which version of modred do you have installed?  I believe that the tutorials, with mr.range and compute_POD_arrays_snaps_method, are correct with respect to the development version of modred available on github.  However, the last public release is different (and older), and has the syntax you describe.  If you are running the latest stable release, you can find the documentation here:  http://modred.readthedocs.io/.

Please let me know if this resolves your issue.

We are working on the next stable release, which is close to being finished, and we hope to get it out soon.  We just have to finalize a few minor details.

**Comment by benoitpaillard** [comment]
Ok sorry for that. I had installed modred with pip. Cloning and install with setup.py works fine.

Thanks for the help and the nice piece of software.
