### ISSUE TITLE
SyntaxError: invalid syntax when running "python setup.py install" but installation seems to succeed

### ISSUE THREAD

**Issue by tolsicsse** [belson17/modred#30]
creating .../lib/python3.7/site-packages/modred-2.0.4.post6-py3.7.egg
Extracting modred-2.0.4.post6-py3.7.egg to .../lib/python3.7/site-packages
  File ".../lib/python3.7/site-packages/modred-2.0.4.post6-py3.7.egg/modred/tests/scaling.py", line 350
    s.barriers / s.total))
                         ^
SyntaxError: invalid syntax

**Comment by jhtu** [comment]
Fixed in 6ea910bb38d300cc39f90acaf6ff4141ad4e7427
