### ISSUE TITLE
Command errored out when installing modred

### ISSUE THREAD

**Issue by enni707** [belson17/modred#31]
python version 3.7.0
numpy version 1.17.4
Platform: windows

pip install modred
Collecting modred
  Using cached https://files.pythonhosted.org/packages/ff/d9/9b65b1ffee0015b7191c63da691f9899e13f23728fc40449206e2f96e470/modred-2.0.4.post6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\XXXX\appdata\local\programs\python\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\XXXX\\AppData\\Local\\Temp\\1\\pip-install-k4ro1oo_\\modred\\setup.py'"'"'; __file__='"'"'C:\\Users\\XXXX\\AppData\\Local\\Temp\\1\\pip-install-k4ro1oo_\\modred\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\XXXX\AppData\Local\Temp\1\pip-install-k4ro1oo_\modred\pip-egg-info'
         cwd: C:\Users\XXXX\AppData\Local\Temp\1\pip-install-k4ro1oo_\modred\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\XXXX\AppData\Local\Temp\1\pip-install-k4ro1oo_\modred\setup.py", line 20, in <module>
        if any(w in ['*a', '*alpha'] for w in parsed_version):
    TypeError: 'Version' object is not iterable
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by luckynew** [comment]
I have met the same error. How can I fix this?

**Comment by jhtu** [comment]
There is something wrong with the current setup.py on PyPI.  We have fixed it, but have not put out the new release yet.  You should install from source for now.  Clone the git repo and follow the instructions for installing from source (basically, you need to run `python setup.py install`).  That should work.  You may also want to build the new documentation, which will reflect other changes made in the codebase for this upcoming release.
