### ISSUE TITLE
IO error during test, commit b909d6f73, file modred/tests/testera.py 

### ISSUE THREAD

**Issue by aparangement** [belson17/modred#40]
line 43:
`self.data_dir = 'files_ERA'`
test with
`python -c 'import modred.tests; modred.tests.run()'`
reports IOerror:
`IOError: files_ERA/A_in1_out1.txt not found.`

**changed to absolute path solves the problem.**

os is ubuntu18.04(python is actually python2.7)

**Comment by jhtu** [comment]
I just pushed a small bug fix.  Can you check for me if this works?  It was not a bug on my Mac or Windows machines, so I cannot verify this myself.  However, I changed the path specification to be more robust, similar to the way it is in the OKID tests, so I suspect this will work.

**Comment by aparangement** [comment]
> I just pushed a small bug fix. Can you check for me if this works? It was not a bug on my Mac or Windows machines, so I cannot verify this myself. However, I changed the path specification to be more robust, similar to the way it is in the OKID tests, so I suspect this will work.

Problem solved, nice work and thanks a lot!
