### ISSUE TITLE
Fails to install using pip

### ISSUE THREAD

**Issue by belson17** [belson17/modred#42]
A user reported that it failed to install properly using python 2.7 and a package manager or the code on https://pypi.org/project/modred, but that he could install it from the source code on git.

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting modred
  Using cached modred-2.0.4.post6.tar.gz (109 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mTJBTf/modred/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mTJBTf/modred/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-VlUsHC
         cwd: /tmp/pip-install-mTJBTf/modred/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mTJBTf/modred/setup.py", line 20, in <module>
        if any(w in ['*a', '*alpha'] for w in parsed_version):
    TypeError: 'Version' object is not iterable
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jhtu** [comment]
As suggested above, this has been fixed.  The `parsed_version` object is cast to a string first, then parsed.  However, in checking this, errors were found in how the version was parsed.  These were fixed in e34a459bbee22e6e29293044ddfb0ea01dfc25f8.
