### ISSUE TITLE
Problem with package installation

### ISSUE THREAD

**Issue by SebiK91** [belson17/modred#45]
Hello everybody,

I’d like to use the Python package ‘modred’ for my master thesis. For this I’d like to install the package first but it doesn’t work.
Attached you can find the following information:
1)	Copy of the entire output of the installation
![Output of the installation](https://user-images.githubusercontent.com/67656312/93016430-60380a00-f5c1-11ea-9758-c802d048f41f.PNG)
2)	Python version
![Python version](https://user-images.githubusercontent.com/67656312/93016432-6332fa80-f5c1-11ea-9f54-da5843143103.PNG)
3)	Numpy version
![Numpy version](https://user-images.githubusercontent.com/67656312/93016434-662deb00-f5c1-11ea-87d5-84dc96e643c6.PNG)
4)	My operating system
![Operating system](https://user-images.githubusercontent.com/67656312/93016438-6af29f00-f5c1-11ea-8188-d588b4ea6cb1.PNG)

I already installed some other packages in the same way.

Do you know where the problem is that I can’t do the installation?

Thanks and Regards
Markus

**Comment by belson17** [comment]
Hi Markus,
I believe this is fixed in the upcoming release. You can clone the github repo and install from source. 

@jhtu is this right, and do you think we're about ready for another release?

**Comment by SebiK91** [comment]
Hi @belson17 
thanks for your quick answer. Cloning the github repo worked without any problems. Thank you very much :-)
