### ISSUE TITLE
Clean up docstrings

### ISSUE THREAD

**Issue by belson17** [belson17/modred#6]
Clean up docstrings so it's all on the same level.  Either include math in docstrings or don't.  Use matrix or vector space notation depending on arrays or handles implementations.  Maybe include an "algorithms" section.

**Comment by jhtu** [comment]
Went through docs for v2.0.0 and cleaned up docstrings.  Made them more consistent in language generally, and now when an identical argument appears in multiple classes, the descriptions are identical too.
